<a href="https://colab.research.google.com/github/Jwoahhh/TH_-Toan_cao_cap/blob/main/B%C3%A0i_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Thực hành 1:** Lặp để tìm nghiệm

In [ ]:
x = 3
print(x)

3


In [ ]:
import math
x = math.sqrt(1+x) 
print(x)

2.0


In [ ]:
x = math.sqrt(1+x) 
print(x)

1.7320508075688772


In [ ]:
x = math.sqrt(1+x) 
print(x)

1.6528916502810695


In [ ]:
x = math.sqrt(1+x) 
print(x)

1.6287699807772333


**Thực hành 2:** Lặp bằng while để tìm nghiệm 

In [ ]:
import math 
x = 3
lap = 1
while (x != math.sqrt(x+1)): 
  x = math.sqrt(x+1) 
  lap = lap  +1 
print(x)
print(lap)

1.618033988749895
32


**Thực hành 3:** Giải phương trình bằng hàm solve trong sympy

In [ ]:
import sympy as sp 
from sympy import Symbol
x = Symbol('x') 
sp.solve(x-sp.sqrt(1+x),x) 


[1/2 + sqrt(5)/2]

**Thực hành 4:** Các phép toán trên vector

In [ ]:
import numpy as np 
v1 = np.array([1., 2., 3.])
v2 = np.array([2., 1., 0.]) 
v3 = v1 + v2 
v3

array([3., 3., 3.])

In [ ]:
3*v1 + 2*v2 

array([7., 8., 9.])

In [ ]:
[1, 2, 3] + [2, 1, 0] 

[1, 2, 3, 2, 1, 0]

In [ ]:
3*[1, 2, 3] + 2*[2, 1, 0] 

[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

In [ ]:
 import numpy as np
 v1 = np.array([1., 2., 3.])
v2 = np.array([2., 1., 0.]) 
 v4 = np.hstack([v1, v2])

In [ ]:
np.dot(v1, v2)

4.0

In [ ]:
angles = np.linspace(0, np.pi/2, 5)
angles

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [ ]:
np.sin(angles) 

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

In [ ]:
import sympy as sy
>>> sy.sin(angles)